services:
  urmainpage:
    image: nginx:latest
    container_name: UrMainPage
    volumes:
     - ./templates:/etc/nginx/templates:ro
     - ./content:/content:ro
    env_file:
     - .env
    network_mode: host
    restart: on-failure

